### PR TITLE
don't use pointers for Multihash.String

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
FYI @masih; ran into this as part of the indexer provider refactor.

Added a couple of other reviewers who can hopefully approve, since Steven seems to be on holiday this week.

**Review by masih — APPROVED** [review]

**Comment by mvdan** [comment]
No profilling/benchmarking; just the API UX. See the commit message.

I'm betting that avoiding the pointer means slightly better perf, but I also imagine it doesn't matter in practice. Especially when compared to the easier-to-use API.

**Review by Kubuxu — APPROVED** [review]
should be backwards compatible

**Comment by mvdan** [comment]
Thanks all for the speedy reviews :)

**Pull request merged**
