### PR TITLE
Add identity

### PR DESCRIPTION
**Pull request by JustinDrake**
See https://github.com/ipfs/go-ipfs/issues/3896 for context

### CODE REVIEW

**Comment by Kubuxu** [comment]
There are not tests for the sum output (this is what codecov complains about).

**Comment by JustinDrake** [comment]
Add output test 👍 

(For future reference, how can I run the CI tests locally on my computer before making a pull-request?)

**Comment by Kubuxu** [comment]
Not really, you can check coverage using `export COVER=$(mktemp) && go test -race -v -coverprofile=$COVER && go tool cover -html=$COVER`. But it is ok to just push and check for results of CI.

**Comment by JustinDrake** [comment]
I think this PR is now ready :)

**Comment by lgierth** [comment]
Cool thanks!

**Pull request merged**
