### PR TITLE
Add md5 hash re: multiformats/multihash#34

### PR DESCRIPTION
**Pull request by eikeon**

### CODE REVIEW

**Comment by eikeon** [comment]
Should have thought to update the tests; should be there now.

**Comment by Stebalien** [comment]
Thanks!

**Comment by hsanjuan** [comment]
Seems this was half-baked.  I'm getting x`Function not implemented. Complain to lib maintainer`.

It seems multihash can represent MD5 but does not know how to create one. I'll open an new PR.

**Comment by eikeon** [comment]
@hsanjuan, sorry about that. I’m only using the part that got baked in my use case so I overlooked the other bit.

**Pull request merged**
