### PR TITLE
Use specific error when base58 didn't work

### PR DESCRIPTION
**Pull request by Kubuxu**
Resolves https://github.com/ipfs/go-ipfs/issues/2916

### CODE REVIEW

**Comment by jbenet** [comment]
LGTM. can you fix CI with this PR?

**Comment by Kubuxu** [comment]
Sure

**Comment by Kubuxu** [comment]
I fixed CI in #28

**Comment by whyrusleeping** [comment]
lets get #28 in, then rebase this and get it merged

**Comment by Kubuxu** [comment]
Rebased.

**Pull request merged**
