### PR TITLE
[WIP] sum: check length of identity hash

### PR DESCRIPTION
**Pull request by schomatis**
Fixes https://github.com/ipfs/go-ipfs/issues/5019.

### CODE REVIEW

**Comment by kevina** [comment]
@Stebalien is there a reason this was merged so fast (less than an hour) without giving me a chance to review it?

**Comment by kevina** [comment]
I think there may be a problem when a length of -1 is passed in, but not sure yet.  It could use a few test cases at least.

**Comment by Stebalien** [comment]
@kevina there was. I merged a second patch to fix that.

I've now reverted both so you can discuss it. Sorry about the confusion, I generally try to merge ASAP when I don't think a change will be controversial as I tend to forget about PRs otherwise. Obviously, this wasn't such a PR...

**Comment by schomatis** [comment]
@kevina Yes, the `-1` would be rejected with this new check. As discussed in the issue I was informed that `-1` is not part of the Multihash specification (if the `-1` signature had been part of it I would just add the check for it in `ValidateCid` and not here).

@Stebalien Since you're around, I could use your take on this one.

**Comment by kevina** [comment]
> @kevina Yes, the -1 would be rejected with this new check. As discussed in the issue I was informed that -1 is not part of the Multihash specification (if the -1 signature had been part of it I would just add the check for it in ValidateCid and not here).

A think you misunderstand.  A -1 length is always valid as part of the prefix and in the case of the id hash it makes a lot of sense since the length is not fixed.

**Comment by Stebalien** [comment]
-1 is part of the go multihash API. It means "use the default". Usually, the check above yours would convert this to an actual length but ID has a default length of -1 meaning "do not truncate".

**Comment by schomatis** [comment]
Thank you both, then I'll revert to the original idea of enforcing the `-1` at the `ValidateCid` level instead of here (which makes more sense IMO).

**Comment by kevina** [comment]
The check is still useful here even if it is also checked elsewhere.  Also specifying the exact length should not be an error.

If I was doing this I would of avoided the special case check and instead changed `sumID` as I said in https://github.com/ipfs/go-ipfs/issues/5019#issuecomment-389620133 but that is more of nit.

**Pull request merged**
